#!/bin/bash
export PATH=$OPENSHIFT_DATA_DIR/jre1.8.0_65/bin:$PATH
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jre1.8.0_65"
export ARTIFACTORY_HOME=$OPENSHIFT_DATA_DIR\artifactory-oss-4.2.0
$ARTIFACTORY_HOME/bin/artifactoryctl stop

client_result "Artifactory stopped"
