#!/bin/bash
export NODENV_ROOT=$OPENSHIFT_DATA_DIR/.nodenv
export PATH="$NODENV_ROOT/bin:$PATH"
eval "$(nodenv init -)"
nodenv rehash
nodenv global 0.12.7
export RBENV_ROOT=$OPENSHIFT_DATA_DIR/.rbenv
export PATH="$RBENV_ROOT/bin:$PATH"
eval "$(rbenv init -)"
rbenv rehash
rbenv global 2.1.6
export RAILS_ENV="production"
